name: one_verse
description: "An complete book experience."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.3.1
  flutter_media_metadata: ^1.0.0+1
  logging: ^1.3.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.1
  audioplayers: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
